services:
        app1:
                container_name: todo-app
                image: callumob/cloud-computing
                ports: 
                        - 80:3000 
                environment:
                        MYSQL_HOST: mysql
                        MYSQL_USER: root 
                        MYSQL_PASSWORD: secret
                        MYSQL_DB: todos

        mysql: 
                image: mysql:8.0
                volumes: 
                        - todo-mysql-data:/var/lib/mysql
                environment:
                        MYSQL_ROOT_PASSWORD: secret
                        MYSQL_DATABASE: todos


        app2:
               container_name: todo-read-only
               image: getting-started-readonly
               ports:
                      - 81:3000
               environment:
                        MYSQL_HOST: mysql
                        MYSQL_USER: root
                        MYSQL_PASSWORD: secret
                        MYSQL_DB: todos
        
volumes: 
        todo-mysql-data:

