services:
        app:
                image: node:18-alpine
                command: sh -c "yarn install && yarn run dev"
                ports:
                        - 81:3000
                working_dir: /app
                volumes:
                        - ./:/app
                environment:
                        MYSQL_HOST: mysql
                        MYSQL_USER: root 
                        MYSQL_PASSWORD: secret
                        MYSQL_DB: todos

volumes: 
        todo-mysql-data:

networks:
        default:
                name: todo-app
                external: true
